import { Routes } from '@angular/router';
import { ProductsComponent } from './products/products.component';
import { ProductDetailComponent } from './product-detail/product-detail.component';
import { LoginComponent } from './login/login.component';
import { SignupComponent } from './signup/signup.component';
import { HomeComponent } from './home/home.component'
import { ProfileComponent } from './profile/profile.component';
import { SellerDashboardComponent } from './seller-dashboard/seller-dashboard.component';
import { ProductFormComponent } from './product-form/product-form.component';
import { ManageMediaComponent } from './manage-media/manage-media.component';
import { NotFoundComponent } from './not-found/not-found.component';
import { BadRequest } from './bad-request/bad-request';
import { Conflict } from './conflict/conflict';
import { Forbidden } from './forbidden/forbidden';
import { ServerError } from './server-error/server-error';
import { NotAuthorizedComponent } from './not-authorized/not-authorized.component';
import { EditProfileComponent } from './edit-profile/edit-profile.component';
import { Cart } from './cart/cart';
import { Checkout } from './checkout/checkout';
import { Orders } from './orders/orders';
import { OrderDetail } from './order-detail/order-detail';
import { AboutPage } from './about-page/about-page';


export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'about', component: AboutPage },
  { path: 'products', component: ProductsComponent },
  { path: 'products/:id', component: ProductDetailComponent },
  { path: 'login', component: LoginComponent },
  { path: 'signup', component: SignupComponent },
  { path: 'profile', component: ProfileComponent },
  { path: 'edit-profile/:id', component: EditProfileComponent },
  { path: 'profile/:id', component: ProfileComponent },
  { path: 'create-product', component: ProductFormComponent },
  { path: 'edit-product/:id', component: ProductFormComponent },
  { path: 'media-product/:id', component: ManageMediaComponent },
  { path: 'orders', component: Orders },
  { path: 'orders/:id', component: OrderDetail },
  { path: 'cart', component: Cart },
  { path: 'checkout', component: Checkout },
  { path: 'bad-request', component: BadRequest },
  { path: 'conflict', component: Conflict },
  { path: 'forbidden', component: Forbidden },
  { path: 'not-found', component: NotFoundComponent },
  { path: 'unauthorized', component: NotAuthorizedComponent },
  { path: 'server-error', component: ServerError },
  { path: '**', component: NotFoundComponent }
];
